<?php
header('Cache-Control: no-store, max-age=0');
function asset_url(string $name): string { return $name . '?v=' . filemtime(__DIR__ . '/' . $name); }
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Margin — A space for your next draft</title><link rel="stylesheet" href="<?= asset_url('assets/style.css') ?>"></head>
<body>
<div class="app">
<aside class="library" id="library">
<a class="brand" href="./"><span class="brand-icon">m</span>margin<span class="brand-dot">.</span></a>
<div class="workspace"><span class="workspace-avatar">Y</span><div>Your workspace<small>A little room to write.</small></div><span class="chevron">⌄</span></div>
<div class="library-heading"><span>YOUR DOCUMENTS</span><button id="new-document" title="New document" class="icon-button">＋</button></div>
<div class="library-controls"><div class="library-search"><span aria-hidden="true">⌕</span><input id="document-search" type="search" aria-label="Search document titles and text" placeholder="Find a document…" autocomplete="off"><button id="clear-document-search" aria-label="Clear document search" hidden>×</button></div><div class="library-filters"><select id="document-filter" aria-label="Filter documents"><option value="all">All documents</option><option value="writing">Writing</option><option value="tests">Score tests</option></select><select id="document-sort" aria-label="Sort documents"><option value="recent">Recent first</option><option value="name">Title A–Z</option><option value="oldest">Oldest first</option></select></div><div id="library-count" class="library-count" role="status"></div><button id="show-current-document" class="show-current-document" hidden>↳ Show current document</button></div>
<nav id="document-list" aria-label="Documents"></nav>
<button class="new-document" id="new-document-bottom">＋ <span>New document</span></button>
<button type="button" id="writing-settings" class="writing-settings-button">⚙ <span>Writing settings</span></button>
<div class="library-bottom"><div class="capture-light"></div><div>Every step, remembered<small>Your writing process is captured.</small></div><button id="capture-toggle" title="Pause or resume recording" class="icon-button">Ⅱ</button></div>
</aside>
<main>
<header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" id="menu-toggle" aria-label="Toggle documents">☰</button><span>Workspace</span><span class="crumb-slash">/</span><span id="breadcrumb-title">The art of paying attention</span></div><div class="topbar-actions"><span id="save-status"><span class="status-dot"></span>Saved locally</span><button class="button quiet" id="workspace-backup" title="Download all documents, revisions, and logs">↓ Backup</button><button class="button quiet" id="export-button">↗ <span>Export</span></button></div></header>
<div class="document-toolbar"><div class="tabs"><button class="tab active" data-view="write">Write</button><button class="tab" data-view="revisions">Revisions <span id="revision-count">2</span></button><button class="tab" data-view="analysis">Word analysis</button><button class="tab" data-view="score">Writing score</button><button class="tab" data-view="process">Writing process <span class="tiny-dot"></span></button></div><button class="button checkpoint" id="checkpoint-button">⊕ <span>Save checkpoint</span></button></div>
<div id="storage-notice" class="storage-notice" role="alert" hidden><span id="storage-notice-text"></span></div>
<section id="write-view" class="view active">
<div class="editor-layout"><article class="paper"><div class="document-label"><span class="label-dot"></span> ESSAY <span class="label-divider">/</span> DRAFT <span id="draft-number">03</span></div><input id="document-title" aria-label="Document title" value="The art of paying attention"><div class="document-meta"><span id="document-date">October 1, 2026</span><span>·</span><span id="reading-time">3 min read</span><span class="draft-badge">Work in progress</span></div>
<div class="format-toolbar"><span class="text-style">Body text <span>⌄</span></span><span class="toolbar-divider"></span><button id="highlight-button" title="Comment on selected text"><span class="highlight-icon">▰</span><span>Add comment</span></button><span class="toolbar-divider"></span><button id="undo-button" title="Undo">↶</button><button id="redo-button" title="Redo">↷</button><span class="toolbar-hint">Make room for a better sentence.</span></div>
<div class="writing-area"><div id="text-backdrop" aria-hidden="true"></div><textarea id="editor" spellcheck="false" autocorrect="on" aria-label="Document body"></textarea></div>
<div class="paper-footer"><span><span class="small-leaf">✧</span> A draft is a beginning, not a verdict.</span><span id="word-count">0 words</span></div></article>
<aside class="comments-panel"><div class="comments-heading"><div><span class="comment-icon">▤</span> In the margins <span id="comment-count">3</span></div><button class="icon-button" id="add-comment" title="Add comment">＋</button></div><p class="comments-subtitle">A second look, a little more clarity.</p><div class="comment-navigation"><span id="suggestion-position">1 of 3 suggestions</span><div><button id="previous-comment" aria-label="Previous suggestion">←</button><button id="next-comment" aria-label="Next suggestion">→</button></div></div><div id="comments-list"></div><div class="comment-tip"><span>✧</span><p>Good writing is rewriting.<br><small>Select a passage to leave a thought.</small></p></div></aside></div>
</section>
<section id="revisions-view" class="view secondary-view"><div class="section-eyebrow">THE EVOLUTION OF YOUR DRAFT</div><h1>Room to revise.</h1><p class="section-description">Every checkpoint keeps a version of your words. Flag the moments that changed the direction.</p><div id="revisions-list"></div></section>
<section id="process-view" class="view secondary-view"><div class="section-eyebrow">BEHIND THE WORDS</div><h1>Your writing, in motion.</h1><p class="section-description">Revisit the pauses, the passages, and the small decisions that make a draft.</p><div class="process-stats" id="process-stats"></div><div class="replay-card"><div class="replay-heading"><h3>Session replay</h3><button id="play-replay" class="button">▶ Play</button></div><input type="range" id="replay-slider" min="0" max="0" value="0" aria-label="Replay event"><div id="replay-detail"></div><pre id="replay-text"></pre></div><div class="event-heading"><h3>Process log</h3><button class="button quiet" id="export-log">↓ Export JSON</button></div><div id="event-list"></div></section>
<section id="analysis-view" class="view secondary-view analysis-view"><div class="section-eyebrow">THE STORY OF EVERY WORD</div><h1>Words, under the surface.</h1><p class="section-description">Trace the words in your latest checkpoint back through the writing process.</p>
<div class="analysis-source"><div><strong id="analysis-checkpoint">No checkpoint yet</strong><small id="analysis-source-date"></small></div><button class="button quiet" id="export-analysis">↓ Export analysis JSON</button></div>
<details class="analysis-method"><summary>How to read this table</summary><p><strong>Before / after</strong> are intervals between document text-input events, measured around the inputs that created the first and last surviving letters. Spaces and punctuation count as inputs. Intervals may include time spent in the sidebar or another window. Missing boundaries, unrecorded text, and transferred words show — rather than an invented pause.</p><p><strong>History:</strong> T = typed, I = inserted into an existing word, D = deleted, R = replaced, P = external paste, C = matched internal copy, M = matched internal cut-and-paste, B = bulk input. @ is the source character offset (zero-based). Expand a row for each individual operation and its timestamp. Shared ancestry after word splits, joins, or passage replacement is flagged. Copy/move links are inferred from the last recorded selection and matching pasted text in this document; cross-document and external pastes have no known source.</p><p><strong>Purity</strong> is a heuristic: 100 ÷ (1 + revision operations + transfer/bulk penalty + shared-lineage penalty), rounded. Straightforward typing scores 100. Incomplete ancestry is unknown, never 100. It measures editing history, not quality. Pauses use text inputs rather than keydown events, so mobile input and punctuation follow the same rule.</p></details>
<div id="analysis-warning" role="status"></div><div class="process-stats" id="analysis-stats"></div>
<div class="analysis-display-toolbar"><div class="analysis-display-toggle" role="group" aria-label="Word analysis display"><button type="button" id="analysis-show-heatmap" class="active" aria-pressed="true" aria-controls="analysis-heatmap-panel">Heatmap</button><button type="button" id="analysis-show-table" aria-pressed="false" aria-controls="analysis-table-panel">Table</button></div><p>Latest checkpoint · Tap a word to inspect its history</p></div>
<div id="analysis-heatmap-panel"><div class="heatmap-legend" aria-label="Heatmap color scale"><span><i class="heat-untouched"></i>Typed once</span><span><i class="heat-light"></i>Lightly edited</span><span><i class="heat-moderate"></i>More edited</span><span><i class="heat-heavy"></i>Heavily edited</span><span><i class="heat-unknown"></i>Unknown history</span></div><div id="word-heatmap" class="word-heatmap" aria-label="Checkpoint text with editing heatmap"></div><p class="heatmap-explanation">Color follows purity: green is 100; yellow and orange indicate more revision, transfer, or shared ancestry. Gray hatching means the history is incomplete.</p><section id="heatmap-word-detail" class="heatmap-word-detail" aria-label="Selected word history" aria-live="polite"><p>Select a word to see how it changed.</p></section></div>
<div id="analysis-table-panel" class="analysis-table-wrap" hidden><table class="analysis-table"><thead><tr><th scope="col">#</th><th scope="col">Word</th><th scope="col">Pause before</th><th scope="col">Pause after</th><th scope="col">Purity</th><th scope="col">Word history</th></tr></thead><tbody id="analysis-rows"></tbody></table></div><p class="analysis-footnote">One row per occurrence, in document order. Hover or tap an interval to inspect its meaning. Unsaved edits after the checkpoint are excluded.</p></section>
<section id="score-view" class="view secondary-view score-view"><div class="section-eyebrow">A LAB FOR THE WRITING PROCESS</div><h1>A session, in shorthand.</h1><p class="section-description">Turn a writing score into a test document, replay its events, and inspect its words. Import always creates a new document.</p>
<div class="score-grid"><div class="score-inputs"><label class="score-checkbox score-format"><input type="checkbox" id="score-extended" checked> Generate faithful notation (navigation, selections, and clipboard actions)</label><label for="score-source">Writing score</label><textarea id="score-source" spellcheck="false" placeholder="&lt;1.2&gt;Hell&lt;0.4&gt;o&lt;ENTER&gt;A draft.&lt;CLICK0&gt;"></textarea><div class="score-actions"><button class="button" id="score-sample">Load example</button><button class="button" id="score-portable">Make portable</button><button class="button" id="score-preview">Preview & validate</button><button class="button score-primary" id="score-import">Create test document</button></div>
<label for="score-expected">Expected final text / generator target</label><textarea id="score-expected" spellcheck="false" placeholder="Paste expected text for exact validation, or enter the final text you want to generate."></textarea><div class="score-generator"><div><label for="score-seed">Random seed</label><input id="score-seed" value="margin-1"></div><div><label for="score-edits">Edit passes</label><input id="score-edits" type="number" min="0" max="50" value="5"></div><button class="button" id="score-generate">✧ Generate score</button></div>
<label for="score-title">Test document title</label><input id="score-title" value="Writing score test"></div>
<div class="score-results"><div class="score-preview-heading"><h3>Reconstructed text</h3><span id="score-validation" role="status">Ready to preview</span></div><pre id="score-final">Load the example, paste a score, or generate a session.</pre><div id="score-metrics"></div><div id="score-messages" role="status"></div><div class="score-export"><h3>From the current document</h3><label for="score-export-format">Score format</label><select id="score-export-format"><option value="faithful">Faithful actions (recommended)</option><option value="basic">Basic compatibility</option></select><label class="score-checkbox"><input type="checkbox" id="score-lossless"> Include lossless log archive</label><p>Faithful scores preserve recorded actions without inventing clicks. Basic compatibility reproduces text for simpler renderers, but may add cursor-positioning clicks.</p><div class="score-actions"><button class="button" id="score-from-document">Load its score</button><button class="button quiet" id="score-download">↓ Download score</button></div></div></div></div>
<details class="analysis-method"><summary>Score notation and timing</summary><p><code>&lt;2.329&gt;</code> advances time by 2.329 seconds. <code>&lt;DEL3&gt;</code> backspaces three UTF-16 units; <code>&lt;DEL&gt;</code> backspaces one. <code>&lt;CLICK31&gt;</code> moves to zero-based offset 31. <code>&lt;ENTER&gt;</code> inserts a newline. A delete with a selection removes that selection. Clicks and selections outside the document are rejected.</p><p>Faithful notation is the default. Keyboard moves appear as LEFT, RIGHT, UP, DOWN, HOME, END, or modified keys, with recorded target ranges after @. CLICK and TAP indicate recorded pointer actions. MOVE and SELECT mark recorded positions whose cause is unknown in older logs. Click Make portable for simpler renderers; this may add positioning clicks and change action provenance.</p><p>Optional extensions: <code>&lt;SELECT2:8&gt;</code>, <code>&lt;COPY&gt;</code>, <code>&lt;CUT&gt;</code>, <code>&lt;PASTE&gt;</code>, <code>&lt;FWD&gt;</code>, <code>&lt;TAB&gt;</code>, and <code>&lt;LT&gt;</code> / <code>&lt;GT&gt;</code> for literal angle brackets. Encoded PATCH and BASE tokens preserve bulk edits and snapshots. Unsupported tokens stay in the log with a warning.</p><p>Plain typing runs have no individual letter timings: their letters share the run timestamp, and word analysis marks intra-run intervals as unknown. Generated scores provide a delay for each letter. These are synthetic sessions, not measurements of real typing. A fixed seed and target give the same score. The lossless RICH extension preserves an entire document; importing it forks the document and remaps IDs.</p></details></section>
<footer class="app-footer"><span><span class="record-dot"></span> <span id="recording-status">Process recording on</span><span class="footer-divider">·</span><span id="event-count">0 events captured</span></span><span>Space for your words. Insight into your process.</span></footer>
</main></div>
<dialog id="writing-settings-dialog" aria-labelledby="writing-settings-title"><div class="dialog-heading"><h2 id="writing-settings-title">Writing settings</h2><button type="button" id="close-writing-settings" class="icon-button" aria-label="Close writing settings">×</button></div><p class="writing-settings-intro">Keep automatic corrections while avoiding the tap menu on underlined words. These preferences apply to this browser.</p><label class="writing-setting"><input type="checkbox" id="setting-spellcheck"><span><strong>Spelling underlines</strong><small>Show the browser’s misspelling marks. Tapping a marked word may also open its correction menu.</small></span></label><label class="writing-setting"><input type="checkbox" id="setting-autocorrect"><span><strong>Automatic corrections</strong><small>Allow the browser or keyboard to replace words as you type. On by default.</small></span></label><p class="writing-settings-note">Browsers do not provide a reliable separate switch for the tap-to-correct menu. Keyboard suggestions can stay visible above the keys.</p><div class="writing-settings-actions"><button type="button" class="button" id="done-writing-settings">Done</button></div></dialog>
<dialog id="delete-document-dialog" aria-labelledby="delete-document-title"><div class="dialog-heading"><h2 id="delete-document-title">Delete this document?</h2><button type="button" id="close-delete-document" class="icon-button" aria-label="Close">×</button></div><p id="delete-document-message"></p><p class="delete-document-note">Its draft, checkpoints, comments, and writing log will be deleted. Download a backup first if you want a copy.</p><div class="delete-document-actions"><button type="button" class="button quiet" id="cancel-delete-document">Keep document</button><button type="button" class="button delete-danger" id="confirm-delete-document">Delete document</button></div></dialog>
<dialog id="comment-dialog"><form id="comment-form"><div class="dialog-heading"><h2>A thought in the margin</h2><button type="button" id="close-dialog" class="icon-button" aria-label="Close">×</button></div><blockquote id="selected-quote"></blockquote><label for="comment-text">Your comment</label><textarea id="comment-text" placeholder="What could this passage become?" required></textarea><label for="comment-kind">Editing pass</label><select id="comment-kind"><option>Clarity</option><option>Voice & tone</option><option>Structure</option><option>Word choice</option><option>General</option></select><button class="button primary" type="submit">Add comment</button></form></dialog>
<div id="toast" role="status"></div><script src="<?= asset_url('assets/text-edits.js') ?>"></script><script src="<?= asset_url('assets/word-analysis.js') ?>"></script><script src="<?= asset_url('assets/word-heatmap.js') ?>"></script><script src="<?= asset_url('assets/writing-score.js') ?>"></script><script src="<?= asset_url('assets/document-library.js') ?>"></script><script src="<?= asset_url('assets/workspace-storage.js') ?>"></script><script src="<?= asset_url('assets/replay.js') ?>"></script><script src="<?= asset_url('assets/app.js') ?>"></script>
</body></html>
