'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {analyze,tokens}=require('../assets/word-analysis.js');
function fixture(initial='') {
 let text=initial,clock=0,id=0;
 const doc={events:[],revisions:[]};
 function event(type,data={},sessionId='session'){clock+=100;const e={id:'e'+(++id),sequence:id,sessionId,timestamp:new Date(1700000000000+clock).toISOString(),elapsedMs:clock,type,data};doc.events.push(e);return e;}
 event('session_start',{text});
 const change=(start,count,insert,inputType='insertText')=>{text=text.slice(0,start)+insert+text.slice(start+count);return event('text_change',{start,deleteCount:count,insert,inputType});};
 const type=s=>{for(const c of s)change(text.length,0,c);};
 const checkpoint=()=>{const r={id:'r'+id,title:'Final',text,date:new Date().toISOString()};const e=event('checkpoint',{revisionId:r.id,text});r.eventSequence=e.sequence;doc.revisions.push(r);return analyze(doc);};
 return {doc,event,change,type,checkpoint,get text(){return text;},snapshot(value,type='recording_resumed'){text=value;event(type,{text});}};
}
test('No checkpoint does not substitute the live draft',()=>{assert.equal(analyze({revisions:[],events:[]}).checkpoint,null);});
test('Straight typing is pure; word occurrences stay distinct and pauses use spaces',()=>{const f=fixture();f.type('cat cat ');const a=f.checkpoint();assert.equal(a.rows.length,2);assert.deepEqual(a.rows.map(r=>r.purity),[100,100]);assert.equal(a.rows[0].history,'T"cat"');assert.equal(a.rows[0].pauseBefore.ms,null);assert.equal(a.rows[0].pauseAfter.ms,100);assert.equal(a.rows[1].pauseBefore.ms,100);assert.equal(a.rows[1].pauseAfter.ms,100);});
test('No following input is unknown, not zero or time until saving',()=>{const f=fixture();f.type('cat');assert.equal(f.checkpoint().rows[0].pauseAfter.ms,null);});
test('Backspacing and correcting a letter preserves the earlier history',()=>{const f=fixture();f.type('cot');f.change(1,1,'a');f.type(' ');const r=f.checkpoint().rows[0];assert.equal(r.word,'cat');assert.equal(r.purity,50);assert.equal(r.history,'T"cot" · R"o"→"a"');});
test('Inserting into an already completed word is a revision',()=>{const f=fixture();f.type('cat ');f.change(3,0,'s');const r=f.checkpoint().rows[0];assert.equal(r.word,'cats');assert.equal(r.purity,50);assert.match(r.history,/I"s"/);});
test('Insertion in the middle cannot score as untouched typing',()=>{const f=fixture();f.type('ct');f.change(1,0,'a');assert.equal(f.checkpoint().rows[0].purity,50);});
test('Delete a whole word then retype retains its lineage',()=>{const f=fixture();f.type('cot');f.change(0,3,'','deleteContentBackward');f.type('cat ');const r=f.checkpoint().rows[0];assert.match(r.history,/T"cot" · D"cot" · T"cat"/);assert.equal(r.purity,50);});
test('Split and join are labelled shared ancestry',()=>{const f=fixture();f.type('sunshine');f.change(3,0,' ');const a=f.checkpoint();assert.deepEqual(a.rows.map(r=>r.word),['sun','shine']);assert.ok(a.rows.every(r=>r.shared && r.purity<100));f.change(3,1,'','deleteContentBackward');const r=f.checkpoint().rows[0];assert.equal(r.word,'sunshine');assert.match(r.history,/D" "/);assert.ok(r.purity<100);});
test('Joining two separately typed words combines both histories',()=>{const f=fixture();f.type('sun shine');f.change(3,1,'','deleteContentBackward');const r=f.checkpoint().rows[0];assert.match(r.history,/T"sun" · T"shine" · D" "/);assert.ok(r.purity<100);});
test('Pre-existing words retain unknown origin after editing',()=>{const f=fixture('old text');f.change(1,1,'a');const a=f.checkpoint();assert.equal(a.rows[0].purity,null);assert.equal(a.rows[1].purity,null);assert.equal(a.rows[0].pauseBefore.ms,null);});
test('Paste from outside has no invented keystroke pauses',()=>{const f=fixture();f.change(0,0,'pasted words','insertFromPaste');const a=f.checkpoint();assert.ok(a.rows.every(r=>r.pauseBefore.ms===null && r.pauseAfter.ms===null && r.purity<100));assert.match(a.rows[0].history,/P"pasted words"/);});
test('Matched internal copy inherits source history and is marked transferred',()=>{const f=fixture();f.type('cat ');f.event('copy',{selectionStart:0,selectionEnd:3});f.change(4,0,'cat','insertFromPaste');const a=f.checkpoint();assert.equal(a.rows[0].purity,100);assert.match(a.rows[1].history,/T"cat" · C←@0 "cat"/);assert.ok(a.rows[1].purity<100);assert.equal(a.rows[1].pauseBefore.ms,null);});
test('Copy history freezes when copied; subsequent source edits do not contaminate it',()=>{const f=fixture();f.type('cat ');f.event('copy',{selectionStart:0,selectionEnd:3});f.change(1,1,'o');f.change(4,0,'cat','insertFromPaste');const a=f.checkpoint();assert.match(a.rows[0].history,/R"a"→"o"/);assert.doesNotMatch(a.rows[1].history,/R/);});
test('Cut then paste preserves original typing and shows the move',()=>{const f=fixture();f.type('cat dog');f.event('cut',{selectionStart:0,selectionEnd:3});f.change(0,3,'','deleteByCut');f.change(f.text.length,0,' ');f.change(f.text.length,0,'cat','insertFromPaste');const r=f.checkpoint().rows.at(-1);assert.match(r.history,/T"cat" · M←@0 "cat"/);assert.equal(r.pauseBefore.ms,null);});
test('Multi-character and IME insertions are bulk, never invented individual typing',()=>{const f=fixture();f.change(0,0,'こんにちは','insertCompositionText');const r=f.checkpoint().rows[0];assert.ok(r.purity<100);assert.equal(r.pauseBefore.ms,null);assert.match(r.history,/B/);});
test('Analysis stops at the checkpoint and excludes subsequent edits',()=>{const f=fixture();f.type('cat ');f.checkpoint();f.change(0,3,'dog');assert.equal(analyze(f.doc).rows[0].word,'cat');assert.equal(analyze(f.doc).rows[0].purity,100);});
test('Legacy checkpoint locates its matching event without eventSequence',()=>{const f=fixture();f.type('cat');f.checkpoint();delete f.doc.revisions[0].eventSequence;assert.equal(analyze(f.doc).rows[0].purity,100);});
test('Seed and unlogged checkpoints have unknown analysis',()=>{const a=analyze({events:[],revisions:[{id:'old',title:'Old',text:'old draft',date:new Date().toISOString()}]});assert.equal(a.rows.length,2);assert.ok(a.rows.every(r=>r.purity===null));assert.equal(a.warnings.length,1);});
test('A mismatched snapshot cannot claim complete history',()=>{const f=fixture();f.type('cat');f.checkpoint();f.doc.revisions[0].text='dog';assert.equal(analyze(f.doc).rows[0].purity,null);});
test('Paused recording and new sessions break pause intervals',()=>{const f=fixture();f.type('cat ');f.event('recording_paused',{text:f.text});f.event('recording_resumed',{text:f.text});f.type('dog ');const a=f.checkpoint();assert.equal(a.rows[1].pauseBefore.ms,null);assert.equal(a.rows[0].pauseAfter.ms,100);});
test('Changes while paused reset unknown lineage',()=>{const f=fixture();f.type('cat');f.snapshot('dog');assert.equal(f.checkpoint().rows[0].purity,null);});
test('Restoring a recorded checkpoint recovers ancestry and flags restoration',()=>{const f=fixture();f.type('cat ');f.checkpoint();const original=f.doc.revisions[0];f.change(0,3,'dog');f.event('revision_restore',{revisionId:original.id,text:original.text});f.snapshot(original.text,'document_open');const r=f.checkpoint().rows[0];assert.equal(r.word,'cat');assert.match(r.history,/Restore/);assert.doesNotMatch(r.history,/R"cat"→"dog"/);assert.ok(r.purity<100);});
test('Unicode and repeated punctuation tokenize without losing occurrences',()=>{assert.deepEqual(tokens("café, don't—café 123 co-op 日本語").map(t=>t.text),['café',"don't",'café','123','co-op','日本語']);});
test('Invalid patches fail closed',()=>{const f=fixture();f.type('cat');f.event('text_change',{start:100,deleteCount:0,insert:'x'});const r=f.checkpoint();assert.equal(r.rows[0].purity,null);assert.match(r.warnings[0],/invalid/);});

test('Replacing an existing word with paste retains its earlier edits',()=>{const f=fixture();f.type('cat');f.change(0,3,'dog','insertFromPaste');const r=f.checkpoint().rows[0];assert.match(r.history,/T"cat" · P"dog"/);assert.ok(r.purity<100);});
test('Nested copying preserves all ancestors through later correction',()=>{const f=fixture();f.type('cat ');f.event('copy',{selectionStart:0,selectionEnd:3});f.change(4,0,'cat','insertFromPaste');f.change(5,1,'o');f.change(7,0,' ');f.event('copy',{selectionStart:4,selectionEnd:7});f.change(8,0,'cot','insertFromPaste');const r=f.checkpoint().rows.at(-1);assert.match(r.history,/T"cat" · C←@0 "cat" · R"a"→"o" · C←@4 "cot"/);});

const {diff}=require('../assets/text-edits.js');
test('Repeated-letter inserts retain their actual selected position',()=>{assert.deepEqual(diff('aaa','aaaa',{selectionStart:0,selectionEnd:0,inputType:'insertText'}),{start:0,deleteCount:0,insert:'a'});});
test('Backward and forward deletion use the pre-input cursor',()=>{assert.deepEqual(diff('aaa','aa',{selectionStart:1,selectionEnd:1,inputType:'deleteContentBackward'}),{start:0,deleteCount:1,insert:''});assert.deepEqual(diff('aaa','aa',{selectionStart:1,selectionEnd:1,inputType:'deleteContentForward'}),{start:1,deleteCount:1,insert:''});});
test('Selected replacement and undo fallback reconstruct the exact text',()=>{const patch=diff('cat dog','cat fox',{selectionStart:4,selectionEnd:7,inputType:'insertFromPaste'});assert.deepEqual(patch,{start:4,deleteCount:3,insert:'fox'});const undo=diff('cat dog','cat fox',{selectionStart:0,selectionEnd:0,inputType:'historyUndo'});assert.equal('cat dog'.slice(0,undo.start)+undo.insert+'cat dog'.slice(undo.start+undo.deleteCount),'cat fox');});

test('An unchanged snapshot after a recording gap cannot claim unedited purity',()=>{const f=fixture();f.type('cat ');f.event('recording_paused',{text:f.text});f.event('recording_resumed',{text:f.text});const a=f.checkpoint();assert.equal(a.rows[0].purity,null);assert.match(a.warnings[0],/paused/);});
test('A checkpoint explicitly captured during pause has incomplete history',()=>{const f=fixture();f.type('cat');f.checkpoint();f.doc.revisions[0].capturePaused=true;assert.equal(analyze(f.doc).rows[0].purity,null);});
