'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {create,indexedDriver}=require('../assets/workspace-storage.js');
const event=id=>({id,sequence:Number(id.slice(1))||1,data:{insert:id}});
const workspace=text=>({version:1,activeId:'doc',documents:[{id:'doc',text,events:[],revisions:[],comments:[]}]});
function legacy(initial){const values=new Map(initial?[['margin-workspace',JSON.stringify(initial)]]:[]);return {getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};}
function memoryDriver(oldSnapshot=null){
 const records={metadata:null,documents:new Map(),heads:new Map(),events:new Map(),revisions:new Map(),comments:new Map()};const commits=[];let snapshot=oldSnapshot;
 const key=r=>JSON.stringify([r.documentId,r.event?.id||r.value.id]);
 return {records,commits,fail:false,async read(){if(!records.metadata)return {workspace:null,legacy:structuredClone(snapshot)};const meta=records.metadata;const documents=meta.documentIds.map(id=>{const head=records.heads.get(id),value=records.documents.get(id).value;return {...structuredClone(value),events:[...records.events.values()].filter(e=>e.documentId===id).sort((a,b)=>a.position-b.position).map(e=>structuredClone(e.event)),revisions:head.revisionIds.map(r=>structuredClone(records.revisions.get(JSON.stringify([id,r])).value)),comments:head.commentIds.map(r=>structuredClone(records.comments.get(JSON.stringify([id,r])).value))};});return {workspace:{...structuredClone(meta.value),documents},legacy:null,generations:Object.fromEntries([...records.heads.values()].map(h=>[h.id,h.generation||0])),metadataGeneration:meta.generation||0};},async commit(batch){if(this.fail){this.fail=false;throw Error('transaction failed');}for(const expected of batch.expectedHeads||[])if((records.heads.get(expected.id)?.generation??null)!==expected.generation)throw Error('changed in another tab');if(batch.metadata&&(records.metadata?.generation??null)!==batch.expectedMetadata)throw Error('changed in another tab');commits.push(structuredClone(batch));if(batch.metadata)records.metadata=structuredClone(batch.metadata);for(const name of ['documents','heads'])for(const r of batch[name])records[name].set(r.id,structuredClone(r));for(const name of ['events','revisions','comments'])for(const r of batch[name]){if(name==='events'&&records.events.has(key(r)))throw Error('duplicate event');records[name].set(key(r),structuredClone(r));}for(const name of ['revisions','comments'])for(const key of batch.removed[name])records[name].delete(JSON.stringify(key));for(const id of batch.removed.documents||[]){records.documents.delete(id);records.heads.delete(id);for(const name of ['events','revisions','comments'])for(const [key,value] of records[name])if(value.documentId===id)records[name].delete(key);}if(batch.migration)snapshot=null;}};
}
test('LocalStorage migration commits separate records before deleting the old key',async()=>{const local=legacy(workspace('old')),driver=memoryDriver();const loaded=await create({localStorage:local,driver}).load();assert.equal(loaded.migrated,true);assert.equal(local.getItem('margin-workspace'),null);assert.equal((await driver.read()).workspace.documents[0].text,'old');assert.equal(driver.commits[0].migration,true);});
test('Version-one IndexedDB snapshot migrates without losing any log, comment or revision',async()=>{const old=workspace('old');old.documents[0].events=[event('e1')];old.documents[0].comments=[{id:'c1',text:'comment'}];old.documents[0].revisions=[{id:'r1',text:'draft',major:true}];const driver=memoryDriver(old);const loaded=await create({localStorage:legacy(),driver}).load();assert.deepEqual(loaded.workspace,old);assert.deepEqual((await driver.read()).workspace,old);assert.equal(driver.records.events.size,1);assert.equal(driver.records.revisions.size,1);assert.equal(driver.records.comments.size,1);});
test('Failed migration leaves old localStorage and version-one snapshots intact',async()=>{const old=workspace('old'),local=legacy(old),driver=memoryDriver(old);driver.fail=true;await assert.rejects(create({localStorage:local,driver}).load(),/transaction/);assert.deepEqual(JSON.parse(local.getItem('margin-workspace')),old);assert.deepEqual((await driver.read()).legacy,old);assert.equal(driver.records.documents.size,0);});
test('One edit writes only its document and new event, not unrelated documents or old history',async()=>{const current=workspace('old');current.documents.push({id:'other',text:'untouched',events:[event('e99')],revisions:[],comments:[]});const driver=memoryDriver();const store=create({localStorage:legacy(),driver});await store.save(current);current.documents[0].text='new';current.documents[0].events.push(event('e1'));await store.save(current);const batch=driver.commits.at(-1);assert.deepEqual(batch.documents.map(d=>d.id),['doc']);assert.deepEqual(batch.events.map(e=>e.event.id),['e1']);assert.equal(batch.revisions.length,0);assert.equal(batch.comments.length,0);assert.equal(batch.metadata,null);assert.deepEqual((await driver.read()).workspace,current);});
test('Navigation writes metadata/new log records but not unchanged document bodies',async()=>{const current=workspace('text');current.documents.push({id:'other',text:'more',events:[],revisions:[],comments:[]});const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.activeId='other';current.documents[1].events.push(event('e1'));await store.save(current);const batch=driver.commits.at(-1);assert.equal(batch.documents.length,0);assert.equal(batch.metadata.value.activeId,'other');assert.equal(batch.events.length,1);});
test('Deleting a document removes its body, checkpoints, comments and events from separate records',async()=>{const current=workspace('keep');current.documents.push({id:'remove',text:'delete me',events:[event('e1')],revisions:[{id:'r1',text:'old'}],comments:[{id:'c1',text:'note'}]});const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents.pop();await store.save(current);assert.deepEqual(driver.commits.at(-1).removed.documents,['remove']);assert.equal(driver.records.documents.has('remove'),false);assert.equal(driver.records.heads.has('remove'),false);for(const name of ['events','revisions','comments'])assert.equal([...driver.records[name].values()].some(r=>r.documentId==='remove'),false);assert.deepEqual((await create({localStorage:legacy(),driver}).load()).workspace,current);});
test('A failed delete leaves stored records intact and can be retried',async()=>{const current=workspace('keep');current.documents.push({id:'remove',text:'delete me',events:[event('e1')],revisions:[],comments:[]});const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents.pop();driver.fail=true;await assert.rejects(store.save(current),/transaction/);assert.equal(driver.records.documents.has('remove'),true);await store.save(current);assert.equal(driver.records.documents.has('remove'),false);assert.deepEqual((await driver.read()).workspace,current);});
test('Queued creation and deletion leave no orphan records',async()=>{const current=workspace('keep'),driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents.push({id:'temporary',text:'draft',events:[event('e1')],revisions:[],comments:[]});const createSave=store.save(current);current.documents.pop();const deleteSave=store.save(current);await Promise.all([createSave,deleteSave]);assert.equal(driver.records.documents.has('temporary'),false);assert.equal([...driver.records.events.values()].some(r=>r.documentId==='temporary'),false);assert.deepEqual((await driver.read()).workspace,current);});
test('LocalStorage fallback persists a document deletion',async()=>{const current=workspace('keep');current.documents.push({id:'remove',text:'delete me',events:[],revisions:[],comments:[]});const local=legacy(),store=create({localStorage:local,indexedDB:null});await store.save(current);current.documents.pop();await store.save(current);assert.deepEqual((await create({localStorage:local,indexedDB:null}).load()).workspace,current);});
test('Revision flags and comment changes update only those records, including after retry',async()=>{const current=workspace('text');current.documents[0].revisions=[{id:'r1',text:'old',major:false}];current.documents[0].comments=[{id:'c1',resolved:false}];const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents[0].revisions[0].major=true;current.documents[0].comments[0].resolved=true;driver.fail=true;await assert.rejects(store.save(current));await store.save(current);assert.equal(driver.commits.at(-1).documents.length,0);assert.equal(driver.commits.at(-1).revisions.length,1);assert.equal(driver.commits.at(-1).comments.length,1);assert.deepEqual((await driver.read()).workspace,current);});
test('Queued saves capture call-time values; a failed append does not lose events in the next save',async()=>{const current=workspace('zero'),driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);driver.fail=true;current.documents[0].text='one';current.documents[0].events.push(event('e1'));const first=store.save(current);current.documents[0].text='two';current.documents[0].events.push(event('e2'));const second=store.save(current);await assert.rejects(first);await second;assert.deepEqual((await driver.read()).workspace,current);assert.deepEqual(driver.commits.at(-1).events.map(r=>r.event.id),['e1','e2']);});
test('Queued reverts retain correct document/record values and do not duplicate event inserts',async()=>{const current=workspace('zero'),driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents[0].text='one';current.documents[0].events.push(event('e1'));const one=store.save(current);current.documents[0].text='zero';current.documents[0].events.push(event('e2'));const two=store.save(current);await one;await two;assert.deepEqual(driver.commits.at(-1).events.map(r=>r.event.id),['e2']);assert.deepEqual((await driver.read()).workspace,current);});
test('Separate records beat stale snapshots and preserve large histories after reload',async()=>{const old=workspace('old'),driver=memoryDriver(old),local=legacy(old);const store=create({localStorage:local,driver});await store.load();local.setItem=()=>{throw Error('QuotaExceededError');};const newer=workspace('new');newer.documents[0].events=[{id:'large',data:'x'.repeat(6000000)}];newer.documents.push({id:'new',text:'new document',events:[],revisions:[],comments:[]});await store.save(newer);const loaded=await create({localStorage:local,driver}).load();assert.deepEqual(loaded.workspace,newer);newer.documents[0].events.push(event('e2'));await store.save(newer);assert.equal(driver.commits.at(-1).events.length,1);});
test('Corrupt reads and shortened histories are rejected without replacing saved records',async()=>{const local=legacy();local.setItem('margin-workspace','broken');await assert.rejects(create({localStorage:local,indexedDB:null}).load(),/cannot be read/);assert.equal(local.getItem('margin-workspace'),'broken');const current=workspace('text');current.documents[0].events=[event('e1')];const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);current.documents[0].events=[];assert.throws(()=>store.save(current),/shortened/);assert.equal(driver.records.events.size,1);});
test('Fallback still rejects quota errors rather than reporting success',async()=>{const local=legacy(workspace('old'));local.setItem=()=>{throw Error('QuotaExceededError');};const store=create({localStorage:local,indexedDB:null});await assert.rejects(store.save(workspace('new')),/Quota/);assert.equal((await store.load()).workspace.documents[0].text,'old');});
test('IndexedDB driver uses version two and resolves only after atomic commit',async()=>{let fail=false,committed=false,version=null;const writes=[];const db={objectStoreNames:{contains:()=>true},transaction(names){assert.ok(names.includes('events')&&names.includes('documents'));const tx={objectStore(name){return {put(value,key){writes.push([name,key]);return {};},add(value,key){writes.push([name,key]);return {};},delete(){return {};}};}};setImmediate(()=>{if(fail){tx.error=Error('aborted');tx.onabort();}else{committed=true;tx.oncomplete();}});return tx;},close(){}};const idb={open(name,v){version=v;const request={};setImmediate(()=>{request.result=db;request.onsuccess();});return request;}};const driver=indexedDriver(idb),batch={metadata:null,documents:[{id:'d',value:{text:'a'}}],heads:[],events:[{documentId:'d',event:event('e1'),position:0}],revisions:[],comments:[],removed:{revisions:[],comments:[]}};await driver.commit(batch);assert.equal(version,2);assert.equal(committed,true);assert.deepEqual(writes,[['documents','d'],['events',['d','e1']]]);fail=true;await assert.rejects(driver.commit(batch),/aborted/);});

test('Stale tabs reject conflicting appends atomically instead of corrupting positions',async()=>{const driver=memoryDriver(),one=create({localStorage:legacy(),driver});const current=workspace('start');await one.save(current);const two=create({localStorage:legacy(),driver});const stale=(await two.load()).workspace;current.documents[0].events.push(event('e1'));current.documents[0].text='first tab';await one.save(current);stale.documents[0].events.push(event('e2'));stale.documents[0].text='second tab';await assert.rejects(two.save(stale),/another tab/);assert.deepEqual((await driver.read()).workspace,current);});
test('Saving an appended event does not traverse or clone the committed history',async()=>{const current=workspace('text');current.documents[0].events=[event('e1')];const driver=memoryDriver(),store=create({localStorage:legacy(),driver});await store.save(current);Object.defineProperty(current.documents[0].events[0],'data',{get(){throw Error('Old history was traversed');},enumerable:true});current.documents[0].events.push(event('e2'));await store.save(current);assert.deepEqual(driver.commits.at(-1).events.map(e=>e.event.id),['e2']);});
