'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const score=require('../assets/writing-score.js');
const {analyze}=require('../assets/word-analysis.js');
function asDoc(result){const revision={id:'final',title:'Final',text:result.text,date:'2026-01-01T00:00:00Z',eventSequence:result.events.length+1};return {id:'doc',title:'Test',text:result.text,comments:[],revisions:[revision],events:[...result.events,{id:'checkpoint',sequence:result.events.length+1,sessionId:result.events.at(-1).sessionId,timestamp:result.events.at(-1).timestamp,elapsedMs:result.elapsedMs,type:'checkpoint',data:{revisionId:'final',text:result.text}}]};}
function replay(events){let text='';for(const e of events){if(typeof e.data.text==='string')text=e.data.text;if(e.type==='text_change')text=text.slice(0,e.data.start)+e.data.insert+text.slice(e.data.start+e.data.deleteCount);}return text;}
test('User fixture reconstructs exact final text, including trailing newlines',()=>{const source=fs.readFileSync(path.join(__dirname,'fixtures/writing-score.txt'),'utf8').replace(/\n$/,'');const r=score.parse(source);assert.equal(source,score.sample);assert.equal(r.text,score.sampleText);assert.equal(r.elapsedMs,131140);assert.equal(r.warnings.length,0);assert.equal(replay(r.events),score.sampleText);assert.equal(new Set(r.events.map(e=>e.id)).size,r.events.length);assert.ok(r.events.every((e,i)=>e.sequence===i+1&&e.data.synthetic));});
test('Imported compact score roundtrips exactly, not only its final text',()=>{const r=score.parse(score.sample);assert.equal(score.exportScore(asDoc(r)).score,score.sample);});
test('Pause applies before text, not after it, and adjacent pauses accumulate',()=>{const r=score.parse('<1><0.25>a<0.125>b<2>');const edits=r.events.filter(e=>e.type==='text_change');assert.deepEqual(edits.map(e=>e.elapsedMs),[1250,1375]);assert.equal(r.elapsedMs,3375);});
test('DEL is backspace and CLICK uses zero-based positions',()=>{assert.equal(score.parse('hello<DEL2>p<CLICK0>T<CLICK3><DEL>').text,'Thlp');});
test('Selection replacement, forward delete, and linebreaks reconstruct',()=>{assert.equal(score.parse('cat dog<SELECT4:7>fox<CLICK0><FWD><ENTER><TAB>').text,'\n\tat fox');});
test('Copy and cut are distinguishable and can paste internally',()=>{const r=score.parse('cat dog<SELECT0:3><COPY><CLICK7> <PASTE><SELECT0:3><CUT><CLICK8><PASTE>');assert.equal(r.text,' dog catcat');assert.ok(r.events.some(e=>e.type==='cut'));assert.ok(r.events.some(e=>e.type==='copy'));assert.ok(r.events.some(e=>e.type==='text_change'&&e.data.inputType==='deleteByCut'));});
test('Unicode typing uses UTF-16 selections but never splits typed codepoints',()=>{assert.equal(score.parse('🙂é<CLICK2>x').text,'🙂xé');assert.throws(()=>score.parse('🙂<CLICK1>'),/surrogate/);assert.throws(()=>score.parse('🙂<DEL>'),/surrogate/);assert.equal(score.parse('🙂<DEL2>').text,'');});
test('Literal angle brackets and token-shaped prose survive roundtrip',()=>{const source='a<LT>DEL3<GT> & café<ENTER>';const r=score.parse(source);assert.equal(r.text,'a<DEL3> & café\n');assert.equal(score.exportScore(asDoc(r),{extended:true}).score,source);});
test('External paste and bulk PATCH preserve their input type',()=>{const source=score.payload('PASTE','hello')+score.payload('PATCH',{start:1,deleteCount:3,insert:'i',inputType:'historyUndo'});const r=score.parse(source);assert.equal(r.text,'hio');assert.equal(r.events.filter(e=>e.type==='text_change').at(-1).data.inputType,'historyUndo');});
test('BASE is a snapshot, not fabricated typing',()=>{const r=score.parse(score.payload('BASE','existing')+'<CLICK8>!');assert.equal(r.text,'existing!');assert.equal(r.events.filter(e=>e.type==='text_change').length,1);assert.equal(analyze(asDoc(r)).rows[0].purity,null);});
test('Unsupported tokens are retained and reported without silently changing text',()=>{const source='a<FOCUSsidebar><1>b';const r=score.parse(source);assert.equal(r.text,'ab');assert.equal(r.warnings.length,1);assert.ok(r.events.some(e=>e.type==='score_unknown'));assert.equal(score.exportScore(asDoc(r),{extended:true}).score,source);});
test('Malformed tokens, out-of-range clicks, and invalid pauses reject',()=>{for(const source of ['hi<CLICK9>','<SELECT3:1>','<DEL0>','<ENTER','<<ENTER>>','<-1>','<Infinity>','<PATCH:invalid>'])assert.throws(()=>score.parse(source));});
test('Deleting beyond the start reports its clamping',()=>{const r=score.parse('a<DEL9>');assert.equal(r.text,'');assert.equal(r.warnings.length,1);});
test('Rich log timestamps and IDs are preserved by the lossless archive',()=>{const d=asDoc(score.parse('a<0.5>b'));d.events.push({id:'focus',sequence:d.events.length+1,sessionId:d.events[0].sessionId,timestamp:'2026-01-01T00:00:00.500Z',elapsedMs:500,type:'focus',data:{area:'sidebar',element:'comment-text'}});d.comments=[{id:'comment',text:'Note'}];const exported=score.exportScore(d,{lossless:true});const imported=score.parse(exported.score);assert.deepEqual(imported.document,d);assert.deepEqual(imported.events,d.events);assert.equal(imported.lossless,true);});
test('An archive that disagrees with visible score is rejected',()=>{const d=asDoc(score.parse('cat'));assert.throws(()=>score.parse('dog'+score.payload('RICH',{version:1,document:d})),/disagree/);});
test('Native event log exports edits and cursor changes with their timing',()=>{const make=(id,ms,type,data)=>({id,sequence:Number(id.slice(1)),sessionId:'s',timestamp:new Date(Date.parse('2026-01-01T00:00:00Z')+ms).toISOString(),elapsedMs:ms,type,data});const d={text:'ax',events:[make('e1',0,'session_start',{text:''}),make('e2',100,'text_change',{start:0,deleteCount:0,insert:'a',inputType:'insertText'}),make('e3',400,'text_change',{start:1,deleteCount:0,insert:'b',inputType:'insertText'}),make('e4',500,'selection',{start:2,end:2}),make('e5',900,'text_change',{start:1,deleteCount:1,insert:'',inputType:'deleteContentBackward'}),make('e6',1500,'text_change',{start:1,deleteCount:0,insert:'x',inputType:'insertText'})]};const r=score.parse(score.exportScore(d).score);assert.equal(r.text,'ax');assert.deepEqual(r.events.filter(e=>e.type==='text_change').map(e=>e.elapsedMs),[100,400,900,1500]);});
test('An imported session with subsequent live edits can export and replay',()=>{const d=asDoc(score.parse('cat<1>'));d.text='cats';d.events.push({id:'live',sequence:d.events.length+1,sessionId:'live-session',timestamp:'2026-01-01T00:00:02Z',elapsedMs:500,type:'text_change',data:{start:3,deleteCount:0,insert:'s',inputType:'insertText'}});const r=score.parse(score.exportScore(d).score);assert.equal(r.text,'cats');assert.equal(replay(r.events),'cats');});
test('Timing absent within a plain run is unknown, explicit pause is measured',()=>{const a=analyze(asDoc(score.parse('<2>cat dog<0.5> ')));assert.equal(a.rows[0].pauseBefore.ms,2000);assert.equal(a.rows[0].pauseAfter.ms,null);assert.equal(a.rows[1].pauseBefore.ms,null);assert.equal(a.rows[1].pauseAfter.ms,500);});
test('Generated letter timing is measured rather than marked as unknown grouping',()=>{const g=score.generate('cat dog ',{seed:'abc',edits:0});const a=analyze(asDoc(score.parse(g.score)));assert.ok(a.rows.every(r=>r.purity===100&&r.pauseBefore.ms>0&&r.pauseAfter.ms>0));});
test('Generation is reproducible and differs across seeds',()=>{const a=score.generate('A target draft.',{seed:'fixed',edits:5});assert.equal(a.score,score.generate('A target draft.',{seed:'fixed',edits:5}).score);assert.notEqual(a.score,score.generate('A target draft.',{seed:'other',edits:5}).score);});
test('One hundred generated sessions all reconstruct their Unicode target',()=>{const target='Writing score\n\nA café, a 🙂, and a draft.\n';for(let i=0;i<100;i++){const g=score.generate(target,{seed:'seed-'+i,edits:i%15});const r=score.parse(g.score);assert.equal(r.text,target);assert.equal(replay(r.events),target);assert.equal(score.parse(score.exportScore(asDoc(r)).score).text,target);}});
test('Generated edits include copies and surviving move provenance',()=>{const g=score.generate('one two three four',{seed:'moves',edits:5,extended:true});assert.match(g.score,/<COPY>/);assert.match(g.score,/<CUT>/);assert.match(g.score,/<PASTE>/);const a=analyze(asDoc(score.parse(g.score)));assert.ok(a.rows.some(r=>/M←/.test(r.history)));assert.ok(a.rows.some(r=>r.purity!==100));});
test('Generator rejects invalid targets and edit settings',()=>{assert.throws(()=>score.generate(''));assert.throws(()=>score.generate('a',{edits:-1}));assert.throws(()=>score.generate('a',{edits:1.5}));assert.throws(()=>score.generate('a'.repeat(5001)));});

// Independent renderer: this deliberately knows nothing about the application's
// extended parser or clipboard implementation, and rejects every non-core token.
function renderBasic(source){let text='',cursor=0;const chunks=source.match(/<[^>]*>|[^<]+/g)||[];for(const chunk of chunks){if(!chunk.startsWith('<')){text=text.slice(0,cursor)+chunk+text.slice(cursor);cursor+=chunk.length;continue;}const value=chunk.slice(1,-1);if(/^\d+(?:\.\d+)?$/.test(value))continue;if(value==='ENTER'){text=text.slice(0,cursor)+'\n'+text.slice(cursor);cursor++;continue;}let match;if((match=/^CLICK(\d+)$/.exec(value))){cursor=Number(match[1]);assert.ok(cursor<=text.length);continue;}if((match=/^DEL(\d*)$/.exec(value))){const from=Math.max(0,cursor-Number(match[1]||1));text=text.slice(0,from)+text.slice(cursor);cursor=from;continue;}throw Error('Unsupported token '+chunk);}return text;}
const regressionText="The birch canoe slid on the smooth planks.\nGlue the sheet to the dark blue background.\nIt's easy to tell the depth of a well.\nThese days a chicken leg is a rare dish.\nRice is often served in round bowls.\nThe juice of lemons makes fine punch.\nThe box was thrown beside the parked truck.\nThe hogs were fed chopped corn and garbage.\nFour hours of steady work faced us.\nA large size in stockings is hard to sell.";
test('Default generator is compatible with an independent basic renderer',()=>{for(let i=0;i<100;i++){const generated=score.generate(regressionText,{seed:'compat-'+i,edits:15});assert.doesNotMatch(generated.score,/<(?:SELECT|COPY|CUT|PASTE|PATCH|BASE|CLIP|RICH)/);assert.equal(renderBasic(generated.score),regressionText);}});
test('Old extended scores can be repaired without shifting cursor positions',()=>{const old=score.generate(regressionText,{seed:'margin-1',edits:20,extended:true});assert.match(old.score,/<SELECT/);assert.throws(()=>renderBasic(old.score),/Unsupported/);const repaired=score.toPortable(old.score);assert.equal(renderBasic(repaired.score),regressionText);assert.equal(score.parse(repaired.score).text,regressionText);assert.equal(score.parse(repaired.score).elapsedMs,score.parse(old.score).elapsedMs);});
test('Default document export lowers selections, clipboard edits, patches and snapshots',()=>{const raw=score.payload('BASE','cat dog')+'<SELECT0:3><COPY><CLICK7> <PASTE><SELECT0:3><CUT><CLICK8><PASTE><SELECT0:4>fox '+score.payload('PATCH',{start:0,deleteCount:3,insert:'new',inputType:'historyUndo'});const d=asDoc(score.parse(raw));const basic=score.exportScore(d);assert.equal(renderBasic(basic.score),d.text);assert.doesNotMatch(basic.score,/<(?:SELECT|COPY|CUT|PASTE|PATCH|BASE|CLIP|RICH)/);assert.ok(basic.warnings.length);assert.match(score.exportScore(d,{extended:true}).score,/<SELECT/);});
test('Portable conversion models selection replacement at the right offset',()=>{const r=score.toPortable('one two<1><SELECT4:7><0.5>three<CLICK0><FWD3>');assert.equal(renderBasic(r.score),' three');assert.equal(score.parse(r.score).elapsedMs,1500);});
test('Basic generation rejects literal control brackets rather than corrupting offsets',()=>{assert.throws(()=>score.generate('a < b'),/angle brackets/);assert.equal(score.parse(score.generate('a < b',{extended:true}).score).text,'a < b');});
